services:
  - type: web
    name: my-personal-blog
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: "10000"
      - key: NODE_ENV
        value: "production"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "24h"
      - key: CORS_ORIGIN
        value: "*"
    plan: free
